import { createFileRoute } from "@tanstack/react-router";
import {
  Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis,
  RadarChart, PolarAngleAxis, PolarGrid, Radar, PolarRadiusAxis,
} from "recharts";
import { Sparkles, ShieldCheck, Cpu } from "lucide-react";
import { KpiCard } from "@/components/soc/KpiCard";
import { Panel } from "@/components/soc/Panel";
import { PageHeader } from "@/components/soc/PageHeader";
import { WorldMap } from "@/components/soc/WorldMap";
import { LiveFeed } from "@/components/soc/LiveFeed";
import { SeverityBadge } from "@/components/soc/SeverityBadge";
import {
  kpis, attackTrend, attacks, aiSummaries, radarThreats, topCountries, alerts,
} from "@/lib/mock-data";
import { sparkData } from "@/components/soc/sparks";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [{ title: "Executive SOC Dashboard — CyberShield AI" }] }),
  component: Index,
});

function Index() {
  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Executive Command Center"
        title="SOC Operations Overview"
        description="Real-time threat posture, attack volumes and AI-generated intelligence across the global estate."
        action={
          <div className="flex items-center gap-2">
            <div className="hidden md:flex items-center gap-2 px-3 h-9 rounded-md border border-border bg-card/40 text-xs">
              <ShieldCheck className="h-3.5 w-3.5 text-[color:var(--neon-green)]" />
              Security Posture <span className="neon-text font-semibold">82</span>/100
            </div>
            <button className="h-9 px-3 rounded-md bg-[color:var(--neon-blue)] text-[color:var(--primary-foreground)] text-xs font-medium flex items-center gap-1.5 glow-blue">
              <Sparkles className="h-3.5 w-3.5" /> Generate Brief
            </button>
          </div>
        }
      />

      <div className="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-4 gap-3">
        {kpis.map((k, i) => (
          <KpiCard key={k.label} {...k} spark={sparkData(i + 1)} />
        ))}
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-4">
        <Panel
          className="xl:col-span-2"
          title="Global Attack Surface"
          subtitle="Live arcs render incoming attacks to SOC HQ"
          action={<span className="text-[10px] text-muted-foreground tracking-widest">LIVE · 6h WINDOW</span>}
          padded={false}
        >
          <div className="h-[360px] p-2"><WorldMap events={attacks} max={70} /></div>
        </Panel>

        <Panel title="AI Threat Summaries" subtitle="Generated by CyberShield AI · Gemini">
          <div className="space-y-3">
            {aiSummaries.map((s) => (
              <div key={s.title} className="rounded-md border border-border bg-card/40 p-3">
                <div className="flex items-center justify-between gap-2 mb-1.5">
                  <div className="text-sm font-medium">{s.title}</div>
                  <SeverityBadge s={s.severity} />
                </div>
                <p className="text-xs text-muted-foreground leading-relaxed">{s.body}</p>
                <div className="mt-2 flex items-center gap-2">
                  <div className="h-1 flex-1 rounded-full bg-secondary overflow-hidden">
                    <div className="h-full bg-gradient-to-r from-[color:var(--neon-blue)] to-[color:var(--neon-cyan)]" style={{ width: `${s.confidence}%` }} />
                  </div>
                  <span className="text-[10px] text-muted-foreground font-mono">{s.confidence}% conf.</span>
                </div>
              </div>
            ))}
          </div>
        </Panel>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-4">
        <Panel className="xl:col-span-2" title="Attack Volume — 24h" subtitle="Attacks vs. blocked vs. anomalies">
          <div className="h-[280px]">
            <ResponsiveContainer>
              <AreaChart data={attackTrend} margin={{ top: 10, right: 10, left: -10, bottom: 0 }}>
                <defs>
                  <linearGradient id="a1" x1="0" x2="0" y1="0" y2="1">
                    <stop offset="0%" stopColor="var(--neon-red)" stopOpacity={0.5} />
                    <stop offset="100%" stopColor="var(--neon-red)" stopOpacity={0} />
                  </linearGradient>
                  <linearGradient id="a2" x1="0" x2="0" y1="0" y2="1">
                    <stop offset="0%" stopColor="var(--neon-cyan)" stopOpacity={0.45} />
                    <stop offset="100%" stopColor="var(--neon-cyan)" stopOpacity={0} />
                  </linearGradient>
                </defs>
                <CartesianGrid stroke="var(--color-border)" strokeDasharray="3 3" vertical={false} />
                <XAxis dataKey="t" stroke="var(--color-muted-foreground)" fontSize={10} tickLine={false} axisLine={false} interval={5} />
                <YAxis stroke="var(--color-muted-foreground)" fontSize={10} tickLine={false} axisLine={false} />
                <Tooltip contentStyle={{ background: "var(--color-popover)", border: "1px solid var(--color-border)", borderRadius: 8, fontSize: 12 }} />
                <Area type="monotone" dataKey="attacks" stroke="var(--neon-red)" fill="url(#a1)" strokeWidth={1.6} />
                <Area type="monotone" dataKey="blocked" stroke="var(--neon-cyan)" fill="url(#a2)" strokeWidth={1.6} />
                <Area type="monotone" dataKey="anomalies" stroke="var(--neon-amber)" fill="none" strokeWidth={1.4} strokeDasharray="3 3" />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </Panel>

        <Panel title="Threat Posture Radar" subtitle="Current vs 30-day baseline">
          <div className="h-[280px]">
            <ResponsiveContainer>
              <RadarChart data={radarThreats}>
                <PolarGrid stroke="var(--color-border)" />
                <PolarAngleAxis dataKey="subject" tick={{ fill: "var(--color-muted-foreground)", fontSize: 11 }} />
                <PolarRadiusAxis tick={{ fill: "var(--color-muted-foreground)", fontSize: 9 }} stroke="var(--color-border)" />
                <Radar name="Baseline" dataKey="baseline" stroke="var(--neon-blue)" fill="var(--neon-blue)" fillOpacity={0.1} />
                <Radar name="Current" dataKey="current" stroke="var(--neon-red)" fill="var(--neon-red)" fillOpacity={0.25} />
              </RadarChart>
            </ResponsiveContainer>
          </div>
        </Panel>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-4">
        <Panel className="xl:col-span-2" title="Live Threat Timeline" subtitle="Streaming events · last 60s" action={<span className="text-[10px] text-[color:var(--neon-red)] animate-blink tracking-widest">● STREAM</span>}>
          <LiveFeed rows={10} />
        </Panel>
        <Panel title="Top Attacking Countries">
          <ul className="space-y-2">
            {topCountries.map((c) => {
              const max = topCountries[0].attacks;
              const pct = (c.attacks / max) * 100;
              return (
                <li key={c.code} className="flex items-center gap-3 text-xs">
                  <span className="font-mono w-8 text-muted-foreground">{c.code}</span>
                  <span className="w-28 truncate">{c.country}</span>
                  <div className="flex-1 h-2 rounded-full bg-secondary overflow-hidden">
                    <div className="h-full bg-gradient-to-r from-[color:var(--neon-red)] to-[color:var(--neon-amber)]" style={{ width: `${pct}%` }} />
                  </div>
                  <span className="font-mono tabular-nums w-14 text-right">{c.attacks.toLocaleString()}</span>
                </li>
              );
            })}
          </ul>
          <div className="mt-4 pt-3 border-t border-border flex items-center gap-2 text-xs text-muted-foreground">
            <Cpu className="h-3.5 w-3.5 text-[color:var(--neon-cyan)]" />
            AI flagged <span className="text-foreground font-semibold mx-1">3</span> regions as elevated risk
          </div>
        </Panel>
      </div>

      <Panel title="Recent Critical Alerts" action={<button className="text-xs text-muted-foreground hover:text-foreground">View all →</button>}>
        <ul className="divide-y divide-border">
          {alerts.slice(0, 6).map((a) => (
            <li key={a.id} className="py-2 flex items-center gap-3 text-xs">
              <SeverityBadge s={a.severity} />
              <span className="font-mono text-muted-foreground w-20">{a.id}</span>
              <span className="font-medium flex-1 truncate">{a.title}</span>
              <span className="text-muted-foreground hidden md:inline">{a.source}</span>
              <span className="text-muted-foreground font-mono w-20 text-right">{new Date(a.ts).toLocaleTimeString([], { hour12: false })}</span>
            </li>
          ))}
        </ul>
      </Panel>
    </div>
  );
}
